with-expecter: true

packages:
  github.com/GulzhanKarakul/payment-service/internal/service:
    config:
      dir: "internal/service/mocks"
      outpkg: "mocks"
    interfaces:
      ClientRepository:
      BusinessRepository:
      BonusSettingsRepository:
      TransactionRepository:
      ClientService:
      BusinessService:
      BonusSettingsService:
      TransactionService: