// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/GulzhanKarakul/payment-service/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockBonusSettingsService is an autogenerated mock type for the BonusSettingsService type
type MockBonusSettingsService struct {
	mock.Mock
}

type MockBonusSettingsService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBonusSettingsService) EXPECT() *MockBonusSettingsService_Expecter {
	return &MockBonusSettingsService_Expecter{mock: &_m.Mock}
}

// GetByBusinessID provides a mock function with given fields: ctx, businessId
func (_m *MockBonusSettingsService) GetByBusinessID(ctx context.Context, businessId string) (domain.BonusSettings, error) {
	ret := _m.Called(ctx, businessId)

	if len(ret) == 0 {
		panic("no return value specified for GetByBusinessID")
	}

	var r0 domain.BonusSettings
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.BonusSettings, error)); ok {
		return rf(ctx, businessId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.BonusSettings); ok {
		r0 = rf(ctx, businessId)
	} else {
		r0 = ret.Get(0).(domain.BonusSettings)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, businessId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBonusSettingsService_GetByBusinessID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByBusinessID'
type MockBonusSettingsService_GetByBusinessID_Call struct {
	*mock.Call
}

// GetByBusinessID is a helper method to define mock.On call
//   - ctx context.Context
//   - businessId string
func (_e *MockBonusSettingsService_Expecter) GetByBusinessID(ctx interface{}, businessId interface{}) *MockBonusSettingsService_GetByBusinessID_Call {
	return &MockBonusSettingsService_GetByBusinessID_Call{Call: _e.mock.On("GetByBusinessID", ctx, businessId)}
}

func (_c *MockBonusSettingsService_GetByBusinessID_Call) Run(run func(ctx context.Context, businessId string)) *MockBonusSettingsService_GetByBusinessID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockBonusSettingsService_GetByBusinessID_Call) Return(_a0 domain.BonusSettings, _a1 error) *MockBonusSettingsService_GetByBusinessID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBonusSettingsService_GetByBusinessID_Call) RunAndReturn(run func(context.Context, string) (domain.BonusSettings, error)) *MockBonusSettingsService_GetByBusinessID_Call {
	_c.Call.Return(run)
	return _c
}

// Upsert provides a mock function with given fields: ctx, businessId, bonusPercent, isActive
func (_m *MockBonusSettingsService) Upsert(ctx context.Context, businessId string, bonusPercent float64, isActive bool) (domain.BonusSettings, error) {
	ret := _m.Called(ctx, businessId, bonusPercent, isActive)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 domain.BonusSettings
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, float64, bool) (domain.BonusSettings, error)); ok {
		return rf(ctx, businessId, bonusPercent, isActive)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, float64, bool) domain.BonusSettings); ok {
		r0 = rf(ctx, businessId, bonusPercent, isActive)
	} else {
		r0 = ret.Get(0).(domain.BonusSettings)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, float64, bool) error); ok {
		r1 = rf(ctx, businessId, bonusPercent, isActive)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBonusSettingsService_Upsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upsert'
type MockBonusSettingsService_Upsert_Call struct {
	*mock.Call
}

// Upsert is a helper method to define mock.On call
//   - ctx context.Context
//   - businessId string
//   - bonusPercent float64
//   - isActive bool
func (_e *MockBonusSettingsService_Expecter) Upsert(ctx interface{}, businessId interface{}, bonusPercent interface{}, isActive interface{}) *MockBonusSettingsService_Upsert_Call {
	return &MockBonusSettingsService_Upsert_Call{Call: _e.mock.On("Upsert", ctx, businessId, bonusPercent, isActive)}
}

func (_c *MockBonusSettingsService_Upsert_Call) Run(run func(ctx context.Context, businessId string, bonusPercent float64, isActive bool)) *MockBonusSettingsService_Upsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(float64), args[3].(bool))
	})
	return _c
}

func (_c *MockBonusSettingsService_Upsert_Call) Return(_a0 domain.BonusSettings, _a1 error) *MockBonusSettingsService_Upsert_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBonusSettingsService_Upsert_Call) RunAndReturn(run func(context.Context, string, float64, bool) (domain.BonusSettings, error)) *MockBonusSettingsService_Upsert_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBonusSettingsService creates a new instance of MockBonusSettingsService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBonusSettingsService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBonusSettingsService {
	mock := &MockBonusSettingsService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
