// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/GulzhanKarakul/payment-service/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockBusinessRepository is an autogenerated mock type for the BusinessRepository type
type MockBusinessRepository struct {
	mock.Mock
}

type MockBusinessRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBusinessRepository) EXPECT() *MockBusinessRepository_Expecter {
	return &MockBusinessRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, name, ownerPhone
func (_m *MockBusinessRepository) Create(ctx context.Context, name string, ownerPhone string) (domain.Business, error) {
	ret := _m.Called(ctx, name, ownerPhone)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 domain.Business
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (domain.Business, error)); ok {
		return rf(ctx, name, ownerPhone)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) domain.Business); ok {
		r0 = rf(ctx, name, ownerPhone)
	} else {
		r0 = ret.Get(0).(domain.Business)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, name, ownerPhone)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBusinessRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockBusinessRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - ownerPhone string
func (_e *MockBusinessRepository_Expecter) Create(ctx interface{}, name interface{}, ownerPhone interface{}) *MockBusinessRepository_Create_Call {
	return &MockBusinessRepository_Create_Call{Call: _e.mock.On("Create", ctx, name, ownerPhone)}
}

func (_c *MockBusinessRepository_Create_Call) Run(run func(ctx context.Context, name string, ownerPhone string)) *MockBusinessRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockBusinessRepository_Create_Call) Return(_a0 domain.Business, _a1 error) *MockBusinessRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBusinessRepository_Create_Call) RunAndReturn(run func(context.Context, string, string) (domain.Business, error)) *MockBusinessRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockBusinessRepository) GetByID(ctx context.Context, id string) (domain.Business, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 domain.Business
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.Business, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.Business); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Business)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBusinessRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockBusinessRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockBusinessRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockBusinessRepository_GetByID_Call {
	return &MockBusinessRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockBusinessRepository_GetByID_Call) Run(run func(ctx context.Context, id string)) *MockBusinessRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockBusinessRepository_GetByID_Call) Return(_a0 domain.Business, _a1 error) *MockBusinessRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBusinessRepository_GetByID_Call) RunAndReturn(run func(context.Context, string) (domain.Business, error)) *MockBusinessRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateBonusBalance provides a mock function with given fields: ctx, id, delta
func (_m *MockBusinessRepository) UpdateBonusBalance(ctx context.Context, id string, delta int64) (domain.Business, error) {
	ret := _m.Called(ctx, id, delta)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBonusBalance")
	}

	var r0 domain.Business
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64) (domain.Business, error)); ok {
		return rf(ctx, id, delta)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int64) domain.Business); ok {
		r0 = rf(ctx, id, delta)
	} else {
		r0 = ret.Get(0).(domain.Business)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int64) error); ok {
		r1 = rf(ctx, id, delta)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBusinessRepository_UpdateBonusBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateBonusBalance'
type MockBusinessRepository_UpdateBonusBalance_Call struct {
	*mock.Call
}

// UpdateBonusBalance is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - delta int64
func (_e *MockBusinessRepository_Expecter) UpdateBonusBalance(ctx interface{}, id interface{}, delta interface{}) *MockBusinessRepository_UpdateBonusBalance_Call {
	return &MockBusinessRepository_UpdateBonusBalance_Call{Call: _e.mock.On("UpdateBonusBalance", ctx, id, delta)}
}

func (_c *MockBusinessRepository_UpdateBonusBalance_Call) Run(run func(ctx context.Context, id string, delta int64)) *MockBusinessRepository_UpdateBonusBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int64))
	})
	return _c
}

func (_c *MockBusinessRepository_UpdateBonusBalance_Call) Return(_a0 domain.Business, _a1 error) *MockBusinessRepository_UpdateBonusBalance_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBusinessRepository_UpdateBonusBalance_Call) RunAndReturn(run func(context.Context, string, int64) (domain.Business, error)) *MockBusinessRepository_UpdateBonusBalance_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBusinessRepository creates a new instance of MockBusinessRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBusinessRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBusinessRepository {
	mock := &MockBusinessRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
