// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/GulzhanKarakul/payment-service/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockTransactionService is an autogenerated mock type for the TransactionService type
type MockTransactionService struct {
	mock.Mock
}

type MockTransactionService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTransactionService) EXPECT() *MockTransactionService_Expecter {
	return &MockTransactionService_Expecter{mock: &_m.Mock}
}

// Cancel provides a mock function with given fields: ctx, id
func (_m *MockTransactionService) Cancel(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Cancel")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTransactionService_Cancel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cancel'
type MockTransactionService_Cancel_Call struct {
	*mock.Call
}

// Cancel is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockTransactionService_Expecter) Cancel(ctx interface{}, id interface{}) *MockTransactionService_Cancel_Call {
	return &MockTransactionService_Cancel_Call{Call: _e.mock.On("Cancel", ctx, id)}
}

func (_c *MockTransactionService_Cancel_Call) Run(run func(ctx context.Context, id string)) *MockTransactionService_Cancel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTransactionService_Cancel_Call) Return(_a0 error) *MockTransactionService_Cancel_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTransactionService_Cancel_Call) RunAndReturn(run func(context.Context, string) error) *MockTransactionService_Cancel_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, clientID, businessID, amount, description
func (_m *MockTransactionService) Create(ctx context.Context, clientID string, businessID string, amount int64, description *string) (domain.Transaction, error) {
	ret := _m.Called(ctx, clientID, businessID, amount, description)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 domain.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int64, *string) (domain.Transaction, error)); ok {
		return rf(ctx, clientID, businessID, amount, description)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int64, *string) domain.Transaction); ok {
		r0 = rf(ctx, clientID, businessID, amount, description)
	} else {
		r0 = ret.Get(0).(domain.Transaction)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, int64, *string) error); ok {
		r1 = rf(ctx, clientID, businessID, amount, description)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTransactionService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTransactionService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - clientID string
//   - businessID string
//   - amount int64
//   - description *string
func (_e *MockTransactionService_Expecter) Create(ctx interface{}, clientID interface{}, businessID interface{}, amount interface{}, description interface{}) *MockTransactionService_Create_Call {
	return &MockTransactionService_Create_Call{Call: _e.mock.On("Create", ctx, clientID, businessID, amount, description)}
}

func (_c *MockTransactionService_Create_Call) Run(run func(ctx context.Context, clientID string, businessID string, amount int64, description *string)) *MockTransactionService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(int64), args[4].(*string))
	})
	return _c
}

func (_c *MockTransactionService_Create_Call) Return(_a0 domain.Transaction, _a1 error) *MockTransactionService_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTransactionService_Create_Call) RunAndReturn(run func(context.Context, string, string, int64, *string) (domain.Transaction, error)) *MockTransactionService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByClientID provides a mock function with given fields: ctx, clientId, limit, offset
func (_m *MockTransactionService) GetByClientID(ctx context.Context, clientId string, limit int, offset int) ([]domain.Transaction, error) {
	ret := _m.Called(ctx, clientId, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetByClientID")
	}

	var r0 []domain.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) ([]domain.Transaction, error)); ok {
		return rf(ctx, clientId, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) []domain.Transaction); ok {
		r0 = rf(ctx, clientId, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) error); ok {
		r1 = rf(ctx, clientId, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTransactionService_GetByClientID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByClientID'
type MockTransactionService_GetByClientID_Call struct {
	*mock.Call
}

// GetByClientID is a helper method to define mock.On call
//   - ctx context.Context
//   - clientId string
//   - limit int
//   - offset int
func (_e *MockTransactionService_Expecter) GetByClientID(ctx interface{}, clientId interface{}, limit interface{}, offset interface{}) *MockTransactionService_GetByClientID_Call {
	return &MockTransactionService_GetByClientID_Call{Call: _e.mock.On("GetByClientID", ctx, clientId, limit, offset)}
}

func (_c *MockTransactionService_GetByClientID_Call) Run(run func(ctx context.Context, clientId string, limit int, offset int)) *MockTransactionService_GetByClientID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockTransactionService_GetByClientID_Call) Return(_a0 []domain.Transaction, _a1 error) *MockTransactionService_GetByClientID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTransactionService_GetByClientID_Call) RunAndReturn(run func(context.Context, string, int, int) ([]domain.Transaction, error)) *MockTransactionService_GetByClientID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockTransactionService) GetByID(ctx context.Context, id string) (domain.Transaction, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 domain.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.Transaction, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.Transaction); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Transaction)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTransactionService_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockTransactionService_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockTransactionService_Expecter) GetByID(ctx interface{}, id interface{}) *MockTransactionService_GetByID_Call {
	return &MockTransactionService_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockTransactionService_GetByID_Call) Run(run func(ctx context.Context, id string)) *MockTransactionService_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTransactionService_GetByID_Call) Return(_a0 domain.Transaction, _a1 error) *MockTransactionService_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTransactionService_GetByID_Call) RunAndReturn(run func(context.Context, string) (domain.Transaction, error)) *MockTransactionService_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTransactionService creates a new instance of MockTransactionService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransactionService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransactionService {
	mock := &MockTransactionService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
