// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/GulzhanKarakul/payment-service/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockClientService is an autogenerated mock type for the ClientService type
type MockClientService struct {
	mock.Mock
}

type MockClientService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClientService) EXPECT() *MockClientService_Expecter {
	return &MockClientService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, phone, name
func (_m *MockClientService) Create(ctx context.Context, phone string, name string) (domain.Client, error) {
	ret := _m.Called(ctx, phone, name)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 domain.Client
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (domain.Client, error)); ok {
		return rf(ctx, phone, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) domain.Client); ok {
		r0 = rf(ctx, phone, name)
	} else {
		r0 = ret.Get(0).(domain.Client)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, phone, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClientService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockClientService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - phone string
//   - name string
func (_e *MockClientService_Expecter) Create(ctx interface{}, phone interface{}, name interface{}) *MockClientService_Create_Call {
	return &MockClientService_Create_Call{Call: _e.mock.On("Create", ctx, phone, name)}
}

func (_c *MockClientService_Create_Call) Run(run func(ctx context.Context, phone string, name string)) *MockClientService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockClientService_Create_Call) Return(_a0 domain.Client, _a1 error) *MockClientService_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClientService_Create_Call) RunAndReturn(run func(context.Context, string, string) (domain.Client, error)) *MockClientService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockClientService) GetByID(ctx context.Context, id string) (domain.Client, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 domain.Client
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.Client, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.Client); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Client)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClientService_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockClientService_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockClientService_Expecter) GetByID(ctx interface{}, id interface{}) *MockClientService_GetByID_Call {
	return &MockClientService_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockClientService_GetByID_Call) Run(run func(ctx context.Context, id string)) *MockClientService_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockClientService_GetByID_Call) Return(_a0 domain.Client, _a1 error) *MockClientService_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClientService_GetByID_Call) RunAndReturn(run func(context.Context, string) (domain.Client, error)) *MockClientService_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByPhone provides a mock function with given fields: ctx, phone
func (_m *MockClientService) GetByPhone(ctx context.Context, phone string) (domain.Client, error) {
	ret := _m.Called(ctx, phone)

	if len(ret) == 0 {
		panic("no return value specified for GetByPhone")
	}

	var r0 domain.Client
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.Client, error)); ok {
		return rf(ctx, phone)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.Client); ok {
		r0 = rf(ctx, phone)
	} else {
		r0 = ret.Get(0).(domain.Client)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, phone)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClientService_GetByPhone_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByPhone'
type MockClientService_GetByPhone_Call struct {
	*mock.Call
}

// GetByPhone is a helper method to define mock.On call
//   - ctx context.Context
//   - phone string
func (_e *MockClientService_Expecter) GetByPhone(ctx interface{}, phone interface{}) *MockClientService_GetByPhone_Call {
	return &MockClientService_GetByPhone_Call{Call: _e.mock.On("GetByPhone", ctx, phone)}
}

func (_c *MockClientService_GetByPhone_Call) Run(run func(ctx context.Context, phone string)) *MockClientService_GetByPhone_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockClientService_GetByPhone_Call) Return(_a0 domain.Client, _a1 error) *MockClientService_GetByPhone_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClientService_GetByPhone_Call) RunAndReturn(run func(context.Context, string) (domain.Client, error)) *MockClientService_GetByPhone_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClientService creates a new instance of MockClientService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClientService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClientService {
	mock := &MockClientService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
