// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/GulzhanKarakul/payment-service/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockBonusSettingsRepository is an autogenerated mock type for the BonusSettingsRepository type
type MockBonusSettingsRepository struct {
	mock.Mock
}

type MockBonusSettingsRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBonusSettingsRepository) EXPECT() *MockBonusSettingsRepository_Expecter {
	return &MockBonusSettingsRepository_Expecter{mock: &_m.Mock}
}

// GetByBusinessID provides a mock function with given fields: ctx, businessID
func (_m *MockBonusSettingsRepository) GetByBusinessID(ctx context.Context, businessID string) (domain.BonusSettings, error) {
	ret := _m.Called(ctx, businessID)

	if len(ret) == 0 {
		panic("no return value specified for GetByBusinessID")
	}

	var r0 domain.BonusSettings
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.BonusSettings, error)); ok {
		return rf(ctx, businessID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.BonusSettings); ok {
		r0 = rf(ctx, businessID)
	} else {
		r0 = ret.Get(0).(domain.BonusSettings)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, businessID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBonusSettingsRepository_GetByBusinessID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByBusinessID'
type MockBonusSettingsRepository_GetByBusinessID_Call struct {
	*mock.Call
}

// GetByBusinessID is a helper method to define mock.On call
//   - ctx context.Context
//   - businessID string
func (_e *MockBonusSettingsRepository_Expecter) GetByBusinessID(ctx interface{}, businessID interface{}) *MockBonusSettingsRepository_GetByBusinessID_Call {
	return &MockBonusSettingsRepository_GetByBusinessID_Call{Call: _e.mock.On("GetByBusinessID", ctx, businessID)}
}

func (_c *MockBonusSettingsRepository_GetByBusinessID_Call) Run(run func(ctx context.Context, businessID string)) *MockBonusSettingsRepository_GetByBusinessID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockBonusSettingsRepository_GetByBusinessID_Call) Return(_a0 domain.BonusSettings, _a1 error) *MockBonusSettingsRepository_GetByBusinessID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBonusSettingsRepository_GetByBusinessID_Call) RunAndReturn(run func(context.Context, string) (domain.BonusSettings, error)) *MockBonusSettingsRepository_GetByBusinessID_Call {
	_c.Call.Return(run)
	return _c
}

// Upsert provides a mock function with given fields: ctx, businessID, bonusPercent, isActive
func (_m *MockBonusSettingsRepository) Upsert(ctx context.Context, businessID string, bonusPercent float64, isActive bool) (domain.BonusSettings, error) {
	ret := _m.Called(ctx, businessID, bonusPercent, isActive)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 domain.BonusSettings
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, float64, bool) (domain.BonusSettings, error)); ok {
		return rf(ctx, businessID, bonusPercent, isActive)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, float64, bool) domain.BonusSettings); ok {
		r0 = rf(ctx, businessID, bonusPercent, isActive)
	} else {
		r0 = ret.Get(0).(domain.BonusSettings)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, float64, bool) error); ok {
		r1 = rf(ctx, businessID, bonusPercent, isActive)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBonusSettingsRepository_Upsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upsert'
type MockBonusSettingsRepository_Upsert_Call struct {
	*mock.Call
}

// Upsert is a helper method to define mock.On call
//   - ctx context.Context
//   - businessID string
//   - bonusPercent float64
//   - isActive bool
func (_e *MockBonusSettingsRepository_Expecter) Upsert(ctx interface{}, businessID interface{}, bonusPercent interface{}, isActive interface{}) *MockBonusSettingsRepository_Upsert_Call {
	return &MockBonusSettingsRepository_Upsert_Call{Call: _e.mock.On("Upsert", ctx, businessID, bonusPercent, isActive)}
}

func (_c *MockBonusSettingsRepository_Upsert_Call) Run(run func(ctx context.Context, businessID string, bonusPercent float64, isActive bool)) *MockBonusSettingsRepository_Upsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(float64), args[3].(bool))
	})
	return _c
}

func (_c *MockBonusSettingsRepository_Upsert_Call) Return(_a0 domain.BonusSettings, _a1 error) *MockBonusSettingsRepository_Upsert_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBonusSettingsRepository_Upsert_Call) RunAndReturn(run func(context.Context, string, float64, bool) (domain.BonusSettings, error)) *MockBonusSettingsRepository_Upsert_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBonusSettingsRepository creates a new instance of MockBonusSettingsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBonusSettingsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBonusSettingsRepository {
	mock := &MockBonusSettingsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
