// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/GulzhanKarakul/payment-service/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockClientRepository is an autogenerated mock type for the ClientRepository type
type MockClientRepository struct {
	mock.Mock
}

type MockClientRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClientRepository) EXPECT() *MockClientRepository_Expecter {
	return &MockClientRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, phone, name
func (_m *MockClientRepository) Create(ctx context.Context, phone string, name string) (domain.Client, error) {
	ret := _m.Called(ctx, phone, name)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 domain.Client
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (domain.Client, error)); ok {
		return rf(ctx, phone, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) domain.Client); ok {
		r0 = rf(ctx, phone, name)
	} else {
		r0 = ret.Get(0).(domain.Client)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, phone, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClientRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockClientRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - phone string
//   - name string
func (_e *MockClientRepository_Expecter) Create(ctx interface{}, phone interface{}, name interface{}) *MockClientRepository_Create_Call {
	return &MockClientRepository_Create_Call{Call: _e.mock.On("Create", ctx, phone, name)}
}

func (_c *MockClientRepository_Create_Call) Run(run func(ctx context.Context, phone string, name string)) *MockClientRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockClientRepository_Create_Call) Return(_a0 domain.Client, _a1 error) *MockClientRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClientRepository_Create_Call) RunAndReturn(run func(context.Context, string, string) (domain.Client, error)) *MockClientRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockClientRepository) GetByID(ctx context.Context, id string) (domain.Client, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 domain.Client
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.Client, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.Client); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Client)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClientRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockClientRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockClientRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockClientRepository_GetByID_Call {
	return &MockClientRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockClientRepository_GetByID_Call) Run(run func(ctx context.Context, id string)) *MockClientRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockClientRepository_GetByID_Call) Return(_a0 domain.Client, _a1 error) *MockClientRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClientRepository_GetByID_Call) RunAndReturn(run func(context.Context, string) (domain.Client, error)) *MockClientRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByPhone provides a mock function with given fields: ctx, phone
func (_m *MockClientRepository) GetByPhone(ctx context.Context, phone string) (domain.Client, error) {
	ret := _m.Called(ctx, phone)

	if len(ret) == 0 {
		panic("no return value specified for GetByPhone")
	}

	var r0 domain.Client
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.Client, error)); ok {
		return rf(ctx, phone)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.Client); ok {
		r0 = rf(ctx, phone)
	} else {
		r0 = ret.Get(0).(domain.Client)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, phone)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClientRepository_GetByPhone_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByPhone'
type MockClientRepository_GetByPhone_Call struct {
	*mock.Call
}

// GetByPhone is a helper method to define mock.On call
//   - ctx context.Context
//   - phone string
func (_e *MockClientRepository_Expecter) GetByPhone(ctx interface{}, phone interface{}) *MockClientRepository_GetByPhone_Call {
	return &MockClientRepository_GetByPhone_Call{Call: _e.mock.On("GetByPhone", ctx, phone)}
}

func (_c *MockClientRepository_GetByPhone_Call) Run(run func(ctx context.Context, phone string)) *MockClientRepository_GetByPhone_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockClientRepository_GetByPhone_Call) Return(_a0 domain.Client, _a1 error) *MockClientRepository_GetByPhone_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClientRepository_GetByPhone_Call) RunAndReturn(run func(context.Context, string) (domain.Client, error)) *MockClientRepository_GetByPhone_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateBonusBalance provides a mock function with given fields: ctx, id, bonus
func (_m *MockClientRepository) UpdateBonusBalance(ctx context.Context, id string, bonus int64) (domain.Client, error) {
	ret := _m.Called(ctx, id, bonus)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBonusBalance")
	}

	var r0 domain.Client
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64) (domain.Client, error)); ok {
		return rf(ctx, id, bonus)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int64) domain.Client); ok {
		r0 = rf(ctx, id, bonus)
	} else {
		r0 = ret.Get(0).(domain.Client)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int64) error); ok {
		r1 = rf(ctx, id, bonus)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClientRepository_UpdateBonusBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateBonusBalance'
type MockClientRepository_UpdateBonusBalance_Call struct {
	*mock.Call
}

// UpdateBonusBalance is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - bonus int64
func (_e *MockClientRepository_Expecter) UpdateBonusBalance(ctx interface{}, id interface{}, bonus interface{}) *MockClientRepository_UpdateBonusBalance_Call {
	return &MockClientRepository_UpdateBonusBalance_Call{Call: _e.mock.On("UpdateBonusBalance", ctx, id, bonus)}
}

func (_c *MockClientRepository_UpdateBonusBalance_Call) Run(run func(ctx context.Context, id string, bonus int64)) *MockClientRepository_UpdateBonusBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int64))
	})
	return _c
}

func (_c *MockClientRepository_UpdateBonusBalance_Call) Return(_a0 domain.Client, _a1 error) *MockClientRepository_UpdateBonusBalance_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClientRepository_UpdateBonusBalance_Call) RunAndReturn(run func(context.Context, string, int64) (domain.Client, error)) *MockClientRepository_UpdateBonusBalance_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClientRepository creates a new instance of MockClientRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClientRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClientRepository {
	mock := &MockClientRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
