// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/GulzhanKarakul/payment-service/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockTransactionRepository is an autogenerated mock type for the TransactionRepository type
type MockTransactionRepository struct {
	mock.Mock
}

type MockTransactionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTransactionRepository) EXPECT() *MockTransactionRepository_Expecter {
	return &MockTransactionRepository_Expecter{mock: &_m.Mock}
}

// Cancel provides a mock function with given fields: ctx, id
func (_m *MockTransactionRepository) Cancel(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Cancel")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTransactionRepository_Cancel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cancel'
type MockTransactionRepository_Cancel_Call struct {
	*mock.Call
}

// Cancel is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockTransactionRepository_Expecter) Cancel(ctx interface{}, id interface{}) *MockTransactionRepository_Cancel_Call {
	return &MockTransactionRepository_Cancel_Call{Call: _e.mock.On("Cancel", ctx, id)}
}

func (_c *MockTransactionRepository_Cancel_Call) Run(run func(ctx context.Context, id string)) *MockTransactionRepository_Cancel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTransactionRepository_Cancel_Call) Return(_a0 error) *MockTransactionRepository_Cancel_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTransactionRepository_Cancel_Call) RunAndReturn(run func(context.Context, string) error) *MockTransactionRepository_Cancel_Call {
	_c.Call.Return(run)
	return _c
}

// CreateWithBonus provides a mock function with given fields: ctx, clientID, businessID, amount, bonusPercent, description
func (_m *MockTransactionRepository) CreateWithBonus(ctx context.Context, clientID string, businessID string, amount int64, bonusPercent float64, description *string) (domain.Transaction, error) {
	ret := _m.Called(ctx, clientID, businessID, amount, bonusPercent, description)

	if len(ret) == 0 {
		panic("no return value specified for CreateWithBonus")
	}

	var r0 domain.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int64, float64, *string) (domain.Transaction, error)); ok {
		return rf(ctx, clientID, businessID, amount, bonusPercent, description)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int64, float64, *string) domain.Transaction); ok {
		r0 = rf(ctx, clientID, businessID, amount, bonusPercent, description)
	} else {
		r0 = ret.Get(0).(domain.Transaction)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, int64, float64, *string) error); ok {
		r1 = rf(ctx, clientID, businessID, amount, bonusPercent, description)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTransactionRepository_CreateWithBonus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateWithBonus'
type MockTransactionRepository_CreateWithBonus_Call struct {
	*mock.Call
}

// CreateWithBonus is a helper method to define mock.On call
//   - ctx context.Context
//   - clientID string
//   - businessID string
//   - amount int64
//   - bonusPercent float64
//   - description *string
func (_e *MockTransactionRepository_Expecter) CreateWithBonus(ctx interface{}, clientID interface{}, businessID interface{}, amount interface{}, bonusPercent interface{}, description interface{}) *MockTransactionRepository_CreateWithBonus_Call {
	return &MockTransactionRepository_CreateWithBonus_Call{Call: _e.mock.On("CreateWithBonus", ctx, clientID, businessID, amount, bonusPercent, description)}
}

func (_c *MockTransactionRepository_CreateWithBonus_Call) Run(run func(ctx context.Context, clientID string, businessID string, amount int64, bonusPercent float64, description *string)) *MockTransactionRepository_CreateWithBonus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(int64), args[4].(float64), args[5].(*string))
	})
	return _c
}

func (_c *MockTransactionRepository_CreateWithBonus_Call) Return(_a0 domain.Transaction, _a1 error) *MockTransactionRepository_CreateWithBonus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTransactionRepository_CreateWithBonus_Call) RunAndReturn(run func(context.Context, string, string, int64, float64, *string) (domain.Transaction, error)) *MockTransactionRepository_CreateWithBonus_Call {
	_c.Call.Return(run)
	return _c
}

// GetByClientID provides a mock function with given fields: ctx, clientId, limit, offset
func (_m *MockTransactionRepository) GetByClientID(ctx context.Context, clientId string, limit int, offset int) ([]domain.Transaction, error) {
	ret := _m.Called(ctx, clientId, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetByClientID")
	}

	var r0 []domain.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) ([]domain.Transaction, error)); ok {
		return rf(ctx, clientId, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) []domain.Transaction); ok {
		r0 = rf(ctx, clientId, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) error); ok {
		r1 = rf(ctx, clientId, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTransactionRepository_GetByClientID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByClientID'
type MockTransactionRepository_GetByClientID_Call struct {
	*mock.Call
}

// GetByClientID is a helper method to define mock.On call
//   - ctx context.Context
//   - clientId string
//   - limit int
//   - offset int
func (_e *MockTransactionRepository_Expecter) GetByClientID(ctx interface{}, clientId interface{}, limit interface{}, offset interface{}) *MockTransactionRepository_GetByClientID_Call {
	return &MockTransactionRepository_GetByClientID_Call{Call: _e.mock.On("GetByClientID", ctx, clientId, limit, offset)}
}

func (_c *MockTransactionRepository_GetByClientID_Call) Run(run func(ctx context.Context, clientId string, limit int, offset int)) *MockTransactionRepository_GetByClientID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockTransactionRepository_GetByClientID_Call) Return(_a0 []domain.Transaction, _a1 error) *MockTransactionRepository_GetByClientID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTransactionRepository_GetByClientID_Call) RunAndReturn(run func(context.Context, string, int, int) ([]domain.Transaction, error)) *MockTransactionRepository_GetByClientID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockTransactionRepository) GetByID(ctx context.Context, id string) (domain.Transaction, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 domain.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.Transaction, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.Transaction); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Transaction)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTransactionRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockTransactionRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockTransactionRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockTransactionRepository_GetByID_Call {
	return &MockTransactionRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockTransactionRepository_GetByID_Call) Run(run func(ctx context.Context, id string)) *MockTransactionRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTransactionRepository_GetByID_Call) Return(_a0 domain.Transaction, _a1 error) *MockTransactionRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTransactionRepository_GetByID_Call) RunAndReturn(run func(context.Context, string) (domain.Transaction, error)) *MockTransactionRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTransactionRepository creates a new instance of MockTransactionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransactionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransactionRepository {
	mock := &MockTransactionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
